# Generated by Django 3.0.2 on 2020-09-29 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buddy',
            options={'verbose_name_plural': 'Buddies'},
        ),
        migrations.RemoveField(
            model_name='civilian',
            name='buddy',
        ),
        migrations.AddField(
            model_name='buddy',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='civilian',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='civilian',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='civilian',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='civilian',
            name='is_beeeping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilian',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilian',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='email',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pics/'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='phone',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='type_of_user',
            field=models.CharField(choices=[('civilian', 'civilian'), ('lawyer', 'lawyer')], default='civilian', max_length=30),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='buddy',
            name='phonenumber',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='civilian',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='civilian',
            name='lawyer',
        ),
        migrations.AddField(
            model_name='civilian',
            name='lawyer',
            field=models.ManyToManyField(blank=True, to='main.Lawyer'),
        ),
        migrations.AlterField(
            model_name='civilian',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='civilian',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Plan'),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Plan'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='num_of_buddies',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='num_of_devices',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='num_of_lawyers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(blank=True, max_length=200, null=True)),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('device_name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('token', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('icon', models.ImageField(null=True, upload_to='token_icons/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Beeep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lng', models.FloatField(default=0)),
                ('start_lat', models.FloatField(default=0)),
                ('end_lng', models.FloatField(default=0)),
                ('end_lat', models.FloatField(default=0)),
                ('plan_price', models.IntegerField(default=0)),
                ('beeep_start_time', models.DateTimeField(auto_now_add=True)),
                ('beeep_end_time', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
