# Generated by Django 3.0.2 on 2020-09-29 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200929_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilian',
            name='lawyer',
        ),
    ]
