# Generated by Django 3.0.2 on 2020-09-29 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_civilian_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilian',
            name='lawyer',
            field=models.ManyToManyField(blank=True, to='main.Lawyer'),
        ),
    ]
