# Generated by Django 3.0.2 on 2020-09-29 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_civilian_lawyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilian',
            name='firebase_key',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='firebase_key',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
