# Generated by Django 3.0.2 on 2020-10-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200929_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilian',
            name='firebase_key',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='firebase_key',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
